# Numpy


In [2]:
# Import the numpy library as np
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a + b

array([5, 7, 9])

In [6]:
# Create a numpy array with the elements [1, 2, 3, 4, 5]
a = np.array([1, 2, 3, 4, 5])
type(a)


numpy.ndarray

In [10]:
# Create a numpy array with the elements 1 to 100.
c = np.arange(1, 101)
print(c)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [11]:
# Print the shape of the array from the previous step
c.shape

(100,)

In [14]:
# Create a 2x2 numpy array with elements
# |1, 2|
# |3, 4|
d = np.array([[1,2],[3,4]])
print(d)
d.shape

[[1 2]
 [3 4]]


(2, 2)

In [15]:
# Calculate the sum of all elements in the 2x2 array
d.sum()

np.int64(10)

In [16]:
# Calculate the mean of the elements in the 2x2 array
d.mean()

np.float64(2.5)

In [23]:
# Reshape the 2x2 array to a 1x4 array and print it
d.reshape((1,4))

array([[1, 2, 3, 4]])

# Pandas


In [25]:
# Import the pandas library as pd
import pandas as pd

In [29]:
# Create a pandas DataFrame from the following dictionary:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [23, 25, 30, 22],
    "Score": [85, 90, 88, 95],
}

df = pd.DataFrame(data)
display(df)


Name  Age  Score
0    Alice   23     85
1      Bob   25     90
2  Charlie   30     88
3    David   22     95

In [30]:
# Print the first 2 rows of the DataFrame
df.head(2)

Name  Age  Score
0  Alice   23     85
1    Bob   25     90

In [33]:
# Print the column names of the DataFrame
df.columns
# df.info()

Index(['Name', 'Age', 'Score'], dtype='object')

In [34]:
# Add a new column called 'Passed' that is True if the 'Score' is greater than or equal to 90, otherwise False
df["Pass"] = df["Score"] > 90
df

Name  Age  Score   Pass
0    Alice   23     85  False
1      Bob   25     90  False
2  Charlie   30     88  False
3    David   22     95   True

In [35]:
# Calculate and print the average age of the students
df["Score"].mean()

np.float64(89.5)

In [36]:
df["Score"].sum()

np.int64(358)

In [37]:
df["Score"].std()

np.float64(4.203173404306164)

In [38]:
df.describe()

Age      Score
count   4.000000   4.000000
mean   25.000000  89.500000
std     3.559026   4.203173
min    22.000000  85.000000
25%    22.750000  87.250000
50%    24.000000  89.000000
75%    26.250000  91.250000
max    30.000000  95.000000