# Numpy


In [1]:
# a = [1,2,3,4,5]
# b = [2,3,4,5,6]
# a + b

In [2]:
# Import the numpy library as np
import numpy as np

# print(sum(a)/len(a))

# print(np.mean(a))


In [27]:
# Create a numpy array with the elements [1, 2, 3, 4, 5]
a = [1,2,3,4,5]

a_np = np.array(a)

a_np.mean()
a_np.max()
a_np.min()
a_np.std()
a_np.var()
a_np.argmin()
a_np.argmax()


print(np.argmin(a_np))
print(a_np.argmin())


0
0


In [36]:
# Create a numpy array with the elements 1 to 100.
b = np.arange(start=1,stop=100,step=2)
print(b)



[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [35]:
# Print the shape of the array from the previous step
b.shape

(50,)

In [ ]:
# Create a 2x2 numpy array with elements
# |1, 2|
# |3, 4|
c = [[1, 2, 3], [3, 4, 1], [5,5,5]]
d = np.array(c)
# print(d)
# print(d.shape)
print(d[0,:])
print(d[:1,:])

[1 2 3]
[[1 2 3]]


In [62]:
# Calculate the sum of all elements in the 2x2 array
print(d)
d.sum(axis=1)


[[1 2 3]
 [3 4 1]
 [5 5 5]]


array([ 6,  8, 15])

In [65]:
# Calculate the mean of the elements in the 2x2 array

d.mean(axis=0)


array([3.        , 3.66666667, 3.        ])

In [80]:
# Reshape the 2x2 array to a 1x4 array and print it
a = [[1,2],[3,4]]
a_np = np.array(a)
print(a_np)
b = a_np.reshape(1,4,1)
print(b)

[[1 2]
 [3 4]]
[[[1]
  [2]
  [3]
  [4]]]


# Pandas


In [81]:
# Import the pandas library as pd
import pandas as pd


In [82]:
# Create a pandas DataFrame from the following dictionary:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [23, 25, 30, 22],
    "Score": [85, 90, 88, 95],
}

df = pd.DataFrame(data=data)
df

Name  Age  Score
0    Alice   23     85
1      Bob   25     90
2  Charlie   30     88
3    David   22     95

In [84]:
# Print the first 2 rows of the DataFrame
df.head(2)
df.tail(2)

Name  Age  Score
2  Charlie   30     88
3    David   22     95

In [85]:
# Print the column names of the DataFrame
df.columns


Index(['Name', 'Age', 'Score'], dtype='object')

In [92]:
sr = df["Score"] >= 90

sr.map({True: "Pass", False: "Failed"})

0    Failed
1      Pass
2    Failed
3      Pass
Name: Score, dtype: object

In [ ]:
# Add a new column called 'Passed' that is True if the 'Score' is greater than or equal to 90, otherwise False
sr = df["Score"] >= 90
sr = sr.map({True: "Pass", False: "Failed"})
df["Pass"] = sr
df

Name  Age  Score    Pass
0    Alice   23     85  Failed
1      Bob   25     90    Pass
2  Charlie   30     88  Failed
3    David   22     95    Pass

In [99]:
# Calculate and print the average age of the students
df["Age"].var()

12.666666666666666